formatting:
  ArgumentListWrapping:
    maxLineLength: 140
  FunctionReturnTypeSpacing:
    maxLineLength: 140
  FunctionSignature:
    maxLineLength: 140
  MaximumLineLength:
    maxLineLength: 140
  ParameterListWrapping:
    maxLineLength: 140
  ParameterWrapping:
    maxLineLength: 140
  PropertyWrapping:
    maxLineLength: 140
  Wrapping:
    maxLineLength: 140

naming:
  MatchingDeclarationName:
    active: false # overlaps with formatting>Filename

style:
  MaxLineLength:
    active: false # overlaps with formatting>MaximumLineLength
  ModifierOrder:
    active: false # overlaps with formatting>ModifierOrdering
  NewLineAtEndOfFile:
    active: false # overlaps with formatting>FinalNewline
